name: anydarts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ca-certificates
  - openssl
  - pip:
      - ultralytics
      - wandb
      - albumentations
      - opencv-python
      - yacs
      - pandas
      - matplotlib
