name: holodarts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - pip
  - ca-certificates
  - openssl
  - pip:
      - ultralytics
      - wandb
      - albumentations
      - opencv-python
      - yacs==0.1.8
      - pandas
      - matplotlib
      - Flask
      - flask-cors
#prefix: C:\Users\rgerb\miniforge3\envs\deep-darts
