# Custom HoloDarts dataset
# using YOLO11m pretrained model
# data format: YOLOv11 PyTorch TXT
path: ../dataset/holo_v1
train: train/images
val: val/images
test: test/images
data: ../dataset/holo_v1/data.yaml
cfg: ../training/train_cfg.yaml
model_weights: ../training/yolo11s.pt

#Classes: 5
names:
  0: cal1
  1: cal2
  2: cal3
  3: cal4
  4: dart

board:
  r_board: 0.2255  # radius of full board
  r_double: 0.170  # center bull to outside double wire edge, in m (BDO standard)
  r_treble: 0.1074  # center bull to outside treble wire edge, in m (BDO standard)
  r_outer_bull: 0.0159
  r_inner_bull: 0.00635
  w_double_treble: 0.01  # wire apex to apex for double and treble
